Fix a trivial bug in the sphere pixel shader on nVidia 7000 series cards.
    Shader program link error
    Fragment info
    -------------
    (130) : error C5051: profile does not support conditional returns

Instead of an early return for halo pixels, invert the condition and skip the last part of the fragment shader.